### ISSUE TITLE
Creating timer thread failed!!

### ISSUE THREAD

**Issue by gokul-narayanan1** [ROBOTIS-GIT/ROBOTIS-Framework#62]
I have a manipulator with 6 dynamixel pro servos. I have created a robot manager based on the tutorials provided in the manual of emanual for robotis framework. But when I run the node, it throws an error 

>  Creating timer thread failed!!
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument

I have set the baud rate to 115200.

How to fix this issue?

**Comment by ROBOTIS-zerom** [comment]
"Creating timer thread failed!!" is a message that appears when the pthread_create() function fails.
This can happen because you do not have permission to create a real time priority thread.  
  
1. launch with superuser privileges.  
  - `$ sudo bash`  
  - `# roslaunch manipulator_h_manager manipulator_h_manager.launch`  

or

2. Increase real-time scheduling priority for current user group  
  - `$ sudo bash -c 'echo "@robotis - rtprio 99" > /etc/security/limits.d/robotis-rtprio.conf'`  
  - `robotis` is current user id & group name  
  - Reboot  
  - `$ roslaunch manipulator_h_manager manipulator_h_manager.launch`  

If you try this method and it still fails, please leave a detailed description of the execution method and error messages.

**Comment by ROBOTIS-zerom** [comment]
It is recommended to use a baudrate of 1 Mbps or higher.

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
